FROM maven:ibmjava-alpine AS build

WORKDIR /app

COPY . .

RUN mvn clean package

FROM openjdk:8-alpine

WORKDIR /app

COPY --from=build /app/target/*.jar .

CMD java -Djava.security.egd=file:/dev/./urandom -jar websocket-demo-0.0.1-SNAPSHOT.jar
